# -*- mode: ruby -*-
# vi: set ft=ruby :

GO_FILE = 'go1.4.2.linux-amd64.tar.gz'
GO_URL = "https://storage.googleapis.com/golang/#{GO_FILE}"
GO_SHA1SUM = '5020af94b52b65cc9b6f11d50a67e4bae07b0aff'
GOPATH = '/vagrant'
GO_SOURCE = File.expand_path(ENV['GO_SOURCE'] || '.', __dir__)

remote_origin_url = `git config --file #{GO_SOURCE}/.git/config --get remote.origin.url`.strip
if remote_origin_url.empty?
  GO_PACKAGE = ENV['GO_PACKAGE']
else
  remote_origin_url = remote_origin_url.match(/(?<host>github.com)[:|\/](?<package>.*).git/)
  GO_PACKAGE = "#{remote_origin_url['host']}/#{remote_origin_url['package']}"
end
GO_PACKAGE_PATH = "#{GOPATH}/src/#{GO_PACKAGE}"

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.synced_folder GO_SOURCE, GO_PACKAGE_PATH
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.forward_agent = true
  config.vm.network :private_network, ip: '10.0.0.10'

  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    sudo mkdir /vagrant
    sudo chown -R vagrant:vagrant /vagrant
    mkdir -p "#{GOPATH}/bin" "#{GOPATH}/src" "#{GOPATH}/pkg"

    sudo apt-get -y install git

    echo "Downloading #{GO_URL}"
    wget --no-clobber --quiet #{GO_URL}
    [[ "#{GO_SHA1SUM}" == `sha1sum #{GO_FILE} | cut -d' ' -f1` ]] || exit 1
    sudo tar -C /usr/local -xzf #{GO_FILE}

    echo "export GOPATH=#{GOPATH}" >> /home/vagrant/.profile
    echo "export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin" >> /home/vagrant/.profile
    source /home/vagrant/.profile
    echo "cd #{GO_PACKAGE_PATH}" >> /home/vagrant/.profile

    cd #{GOPATH}
    echo "Downloading #{GO_PACKAGE}"
    go get #{GO_PACKAGE}
  SHELL
end
